version: "3.9"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: dsp_user
      POSTGRES_PASSWORD: dsp_pass
      POSTGRES_DB: dsp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql+psycopg2://dsp_user:dsp_pass@db:5432/dsp
      # EQUATIV_* vars can be added here or via .env
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./backend/frontend
    working_dir: /app
    command: ["npm","run","dev","--","--host","0.0.0.0"]
    volumes:
      - ./backend/frontend:/app
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  pgdata:
